## Documentação do Projeto Titanic
Este projeto analisa dados do Titanic a partir do arquivo titanic.csv. O objetivo é extrair informações sobre passageiras do sexo feminino da primeira classe que sobreviveram ao acidente do Titanic e gerar um novo arquivo CSV com os resultados.

## Passos:

Importação das bibliotecas:

Importa as bibliotecas pandas para manipulação de dados.

## Leitura dos dados:

Lê o arquivo titanic.csv em um DataFrame df.

## Criação de um novo DataFrame:

Cria um novo DataFrame df_novo com as colunas 'Name', 'Age', 'Sex', 'Pclass' e 'Survived' a partir do DataFrame original df.

## Filtragem dos dados:

Filtra o DataFrame df_novo para obter apenas passageiras do sexo feminino da primeira classe, armazenando o resultado em filter1.

## Ordenação dos dados:

Ordena o DataFrame filter1 em ordem alfabética pelo nome, armazenando o resultado em order_asc.

## Exportação dos resultados:

Exporta o DataFrame order_asc para um arquivo CSV chamado titanic_result.csv.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
columns = {
    'Name': df['Name'],
    'Age': df['Age'],
    'Sex': df['Sex'],
    'Pclass': df['Pclass'],
    'Survived': df['Survived']
}

In [ ]:
df_novo = pd.DataFrame(columns)

filter1 = df_novo.loc[(df_novo['Sex'] == 'female') & (df_novo['Pclass'] == 1) & (df_novo['Survived'] == 1)]
filter1

,Name,Age,Sex,Pclass,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1
11,"Bonnell, Miss. Elizabeth",58.0,female,1,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,female,1,1
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.0,female,1,1
...,...,...,...,...,...
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,female,1,1
862,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",48.0,female,1,1
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0,female,1,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,female,1,1
887,"Graham, Miss. Margaret Edith",19.0,female,1,1

In [ ]:
order_asc = filter1.sort_values(['Name'], ascending=True)
order_asc

,Name,Age,Sex,Pclass,Survived
730,"Allen, Miss. Elisabeth Walton",29.0,female,1,1
275,"Andrews, Miss. Kornelia Theodosia",63.0,female,1,1
571,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",53.0,female,1,1
700,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",18.0,female,1,1
369,"Aubart, Mme. Leontine Pauline",24.0,female,1,1
...,...,...,...,...,...
258,"Ward, Miss. Anna",35.0,female,1,1
366,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",60.0,female,1,1
318,"Wick, Miss. Mary Natalie",31.0,female,1,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,female,1,1
325,"Young, Miss. Marie Grice",36.0,female,1,1

In [ ]:
order_asc.to_csv('titanic_result.csv', index=False)